FROM            eb-docker:base
MAINTAINER      lockstom2@gmail.com

ENV             PROJECT_DIR             /srv/project
ENV             BUILD_MODE              dev
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

# dev 용 requirements 설치
COPY            ./requirements.txt  /srv/
RUN             pip install -r /srv/requirements.txt


COPY            .   ${PROJECT_DIR}
WORKDIR         ${PROJECT_DIR}



# Nginx 설정파일들 복사 미 enabled로 링크
            # avaiable에 있는 파일 복사
RUN         cp -f   ${PROJECT_DIR}/.config/${BUILD_MODE}/nginx.conf \
                    /etc/nginx/nginx.conf &&\

            # avaiable 에 nginx_app.conf 파일 복사
            cp -f   ${PROJECT_DIR}/.config/${BUILD_MODE}/nginx_app.conf \
                    /etc/nginx/sites-available/ && \
            # 이미 sites-enabled 에 있던 모든 내용 삭제
            rm -f   /etc/nginx/sites-enabled/* &&\

            # 링크 연결
            ln -sf  /etc/nginx/sites-available/nginx_app.conf \
                    /etc/nginx/sites-enabled

# supervisor 설정 복사
RUN         cp -f   ${PROJECT_DIR}/.config/${BUILD_MODE}/supervisor_app.conf \
                    /etc/supervisor/conf.d/

# Run supervisord
CMD         supervisord -n