FROM            python:3.6.5-slim

MAINTAINER      lockstom2@gmail.com

# uwsgi는 Pipfile에 기록
RUN             apt -y update && apt -y dist-upgrade
RUN             apt -y install build-essential
RUN             apt -y install nginx supervisor



# 로컬의 requirement.txt 파이을 /srv 에 복사 후 pip install 실행
# (build 하는 한경에 requirements.txt 가 있어야 함)
COPY            ./requirements.txt  /srv/
RUN             pip install -r /srv/requirements.txt

