# Generated by Django 2.1 on 2018-08-17 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
        ('members', '0003_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('cancel_at', models.DateTimeField(auto_now=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='reward.Reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='funding',
            field=models.ManyToManyField(blank=True, related_name='funding_list', related_query_name='fundding_list', through='members.Funding', to=settings.AUTH_USER_MODEL),
        ),
    ]
