# Generated by Django 2.0.7 on 2018-07-30 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('product_img', models.CharField(max_length=200)),
                ('period', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.PositiveIntegerField()),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
