# Generated by Django 2.0.7 on 2018-08-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_option',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='reward.Product'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_name',
            field=models.CharField(max_length=200),
        ),
    ]
