# Generated by Django 2.1 on 2018-08-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20180810_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_funding',
            field=models.BooleanField(default=True),
        ),
    ]
