# Generated by Django 2.0.7 on 2018-08-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20180806_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
