# Generated by Django 2.0.7 on 2018-08-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20180731_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='interested_count',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
