# Generated by Django 2.1 on 2018-08-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_product_product_is_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_video_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
